---
- name: Copy Apache tar to managed node
  copy:
    src: /tmp/ansible-apache.tar
    dest: /tmp/ansible-apache.tar
  become: yes

- name: Load Apache image on managed node
  command: docker load -i /tmp/ansible-apache.tar
  become: yes

- name: Run Apache container
  command: docker run -d --name ansible-apache -p 80:80 ansible-apache:latest
  become: yes

- name: Copy Nagios tar to managed node
  copy:
    src: /tmp/ansible-nagios.tar
    dest: /tmp/ansible-nagios.tar
  become: yes

- name: Load Nagios image on managed node
  command: docker load -i /tmp/ansible-nagios.tar
  become: yes

- name: Run Nagios container
  command: docker run -d --name ansible-nagios -p 8080:80 ansible-nagios:latest
  become: yes
